app:
  initializeBooks: true
  useH2Database: false
spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml