--liquibase formatted sql

--changeset Reinis:1
CREATE TABLE books
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    author     VARCHAR(255),
    date_added TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_books PRIMARY KEY (id)
);